// ============================================================================
// App Router — GoRouter Configuration
//
// Defines all application routes with session-based access control.
//
// Route Guard Logic:
// - On app startup: reads session from secure storage
// - If NO session token found: redirect all routes to /setup
// - If session token EXISTS: redirect /setup to /home (already configured)
// - If session is REVOKED (401 from API): interceptor clears session and
//   navigates to /setup programmatically
//
// Phase 1: Placeholder screens — full implementation in Phase 2+
// ============================================================================

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

import '../constants/storage_keys.dart';
import '../secure_storage/secure_storage_service.dart';
import 'route_names.dart';

// Generated by build_runner — run: dart run build_runner build
part 'app_router.g.dart';

// TODO: Replace placeholder widgets with actual screen imports in Phase 2+
// import '../../features/setup/screens/welcome_setup_screen.dart';
// import '../../features/setup/screens/setup_qr_scan_screen.dart';
// import '../../features/home/screens/scanner_home_screen.dart';
// import '../../features/scanner/screens/ticket_scan_screen.dart';
// import '../../features/manual_search/screens/manual_search_screen.dart';
// import '../../features/settings/screens/session_settings_screen.dart';

/// Riverpod provider for the GoRouter instance.
///
/// Using @riverpod annotation generates a provider that can be refreshed
/// when session state changes, triggering route guard re-evaluation.
///
/// The [ref] parameter allows reading other providers (e.g., session state)
/// for use in the redirect guard.
@riverpod
GoRouter appRouter(AppRouterRef ref) {
  return GoRouter(
    // Default route when app starts.
    // The redirect function will override this based on session state.
    initialLocation: RouteNames.setup,

    // Enable debug logging for route transitions in development.
    // Set to false or use kDebugMode check before production release.
    debugLogDiagnostics: true,

    // --------------------------------------------------------------------------
    // Session-based route guard.
    //
    // Called on every navigation attempt (initial and subsequent).
    // Returns null to allow navigation, or a path string to redirect.
    //
    // Logic:
    // 1. Read session token from secure storage
    // 2. If no token: force redirect to /setup
    // 3. If token exists and navigating to /setup: redirect to /home
    //    (user is already configured — no need to show setup again)
    // 4. Otherwise: allow navigation to requested route
    // --------------------------------------------------------------------------
    redirect: (BuildContext context, GoRouterState state) async {
      // TODO: Replace with sessionServiceProvider in Phase 3
      // For Phase 1, read directly from secure storage for simplicity.
      // In Phase 2+, this will use the SessionService provider.
      final storage = ref.read(secureStorageServiceProvider);
      final sessionToken = await storage.read(StorageKeys.sessionToken);

      final bool hasSession = sessionToken != null && sessionToken.isNotEmpty;
      final bool isOnSetupRoute = state.matchedLocation == RouteNames.setup ||
          state.matchedLocation == RouteNames.setupScan;

      // No session: force user to setup screen regardless of requested route.
      if (!hasSession && !isOnSetupRoute) {
        return RouteNames.setup;
      }

      // Has session but trying to access setup: redirect to home.
      // Prevents a configured device from going back to setup accidentally.
      if (hasSession && isOnSetupRoute) {
        return RouteNames.home;
      }

      // Allow navigation to the requested route.
      return null;
    },

    // --------------------------------------------------------------------------
    // Route Definitions
    // --------------------------------------------------------------------------
    routes: [
      // Setup / Welcome Screen
      // Entry point for unconfigured devices.
      GoRoute(
        path: RouteNames.setup,
        name: 'setup',
        builder: (context, state) {
          // TODO: Replace with WelcomeSetupScreen() in Phase 4
          return const _PlaceholderScreen(
            title: 'Welcome Setup',
            subtitle: 'Scan your admin setup QR code to get started.',
            routePath: RouteNames.setup,
          );
        },
      ),

      // Setup QR Scan Screen
      // Camera view for scanning the admin setup QR code.
      GoRoute(
        path: RouteNames.setupScan,
        name: 'setup-scan',
        builder: (context, state) {
          // TODO: Replace with SetupQrScanScreen() in Phase 4
          return const _PlaceholderScreen(
            title: 'Scan Setup QR',
            subtitle: 'Point camera at the admin setup QR code.',
            routePath: RouteNames.setupScan,
          );
        },
      ),

      // Scanner Home Screen
      // Dashboard shown after successful event binding.
      GoRoute(
        path: RouteNames.home,
        name: 'home',
        builder: (context, state) {
          // TODO: Replace with ScannerHomeScreen() in Phase 6
          return const _PlaceholderScreen(
            title: 'Scanner Home',
            subtitle: 'Event dashboard. Session active.',
            routePath: RouteNames.home,
          );
        },
      ),

      // Ticket Scan Screen
      // Full-screen camera view for scanning attendee tickets.
      GoRoute(
        path: RouteNames.scan,
        name: 'scan',
        builder: (context, state) {
          // TODO: Replace with TicketScanScreen() in Phase 7
          return const _PlaceholderScreen(
            title: 'Ticket Scanner',
            subtitle: 'Point camera at attendee ticket QR code.',
            routePath: RouteNames.scan,
          );
        },
      ),

      // Manual Search Screen
      // Manual ticket reference entry for lookup.
      GoRoute(
        path: RouteNames.manualSearch,
        name: 'manual-search',
        builder: (context, state) {
          // TODO: Replace with ManualSearchScreen() in Phase 8
          return const _PlaceholderScreen(
            title: 'Manual Search',
            subtitle: 'Enter ticket reference to search manually.',
            routePath: RouteNames.manualSearch,
          );
        },
      ),

      // Session Settings Screen
      // Device info, session info, logout/reset actions.
      GoRoute(
        path: RouteNames.settings,
        name: 'settings',
        builder: (context, state) {
          // TODO: Replace with SessionSettingsScreen() in Phase 9
          return const _PlaceholderScreen(
            title: 'Settings',
            subtitle: 'Session and device settings.',
            routePath: RouteNames.settings,
          );
        },
      ),
    ],

    // --------------------------------------------------------------------------
    // Error handler for unknown routes.
    // Shows a simple error screen instead of crashing.
    // --------------------------------------------------------------------------
    errorBuilder: (context, state) {
      return Scaffold(
        backgroundColor: Colors.black,
        body: Center(
          child: Padding(
            padding: const EdgeInsets.all(24.0),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                const Icon(
                  Icons.error_outline,
                  color: Colors.red,
                  size: 64,
                ),
                const SizedBox(height: 16),
                const Text(
                  'Page Not Found',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 24,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                const SizedBox(height: 8),
                Text(
                  'Route "${state.uri}" does not exist.',
                  style: const TextStyle(color: Colors.white60),
                  textAlign: TextAlign.center,
                ),
                const SizedBox(height: 24),
                ElevatedButton(
                  onPressed: () => context.go(RouteNames.setup),
                  child: const Text('Go to Setup'),
                ),
              ],
            ),
          ),
        ),
      );
    },
  );
}

// ============================================================================
// PHASE 1 PLACEHOLDER SCREEN
//
// Temporary screen used for all routes during Phase 1 bootstrap.
// Replaced screen by screen in subsequent phases.
//
// Shows the route path, title, and navigation buttons for testing
// that routing works correctly before real screens are built.
// ============================================================================

class _PlaceholderScreen extends StatelessWidget {
  const _PlaceholderScreen({
    required this.title,
    required this.subtitle,
    required this.routePath,
  });

  final String title;
  final String subtitle;
  final String routePath;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFF0A0A0A),
      appBar: AppBar(
        backgroundColor: const Color(0xFF1A1A1A),
        title: Text(
          title,
          style: const TextStyle(color: Colors.white),
        ),
        iconTheme: const IconThemeData(color: Colors.white),
      ),
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.all(24.0),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              // Route indicator badge
              Container(
                padding: const EdgeInsets.symmetric(
                  horizontal: 12,
                  vertical: 6,
                ),
                decoration: BoxDecoration(
                  color: const Color(0xFF1E3A2F),
                  borderRadius: BorderRadius.circular(20),
                  border: Border.all(color: const Color(0xFF2ECC71)),
                ),
                child: Text(
                  'ROUTE: $routePath',
                  textAlign: TextAlign.center,
                  style: const TextStyle(
                    color: Color(0xFF2ECC71),
                    fontSize: 12,
                    fontWeight: FontWeight.w600,
                    fontFamily: 'monospace',
                  ),
                ),
              ),
              const SizedBox(height: 32),

              // Phase 1 banner
              Container(
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  color: const Color(0xFF1A1A1A),
                  borderRadius: BorderRadius.circular(12),
                  border: Border.all(color: const Color(0xFF333333)),
                ),
                child: Column(
                  children: [
                    const Icon(
                      Icons.construction,
                      color: Color(0xFFF39C12),
                      size: 48,
                    ),
                    const SizedBox(height: 16),
                    Text(
                      title,
                      style: const TextStyle(
                        color: Colors.white,
                        fontSize: 22,
                        fontWeight: FontWeight.bold,
                      ),
                      textAlign: TextAlign.center,
                    ),
                    const SizedBox(height: 8),
                    Text(
                      subtitle,
                      style: const TextStyle(
                        color: Colors.white54,
                        fontSize: 14,
                      ),
                      textAlign: TextAlign.center,
                    ),
                    const SizedBox(height: 16),
                    const Text(
                      'Phase 1 Placeholder\nReal screen coming in later phases.',
                      style: TextStyle(
                        color: Color(0xFFF39C12),
                        fontSize: 12,
                      ),
                      textAlign: TextAlign.center,
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 32),

              // Navigation test buttons — only shown in debug mode
              // These are temporary for testing routing in Phase 1
              const Text(
                'TEST NAVIGATION (Phase 1 only)',
                style: TextStyle(
                  color: Colors.white38,
                  fontSize: 11,
                  letterSpacing: 1.2,
                ),
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: 12),
              _buildNavButton(context, 'Setup', RouteNames.setup),
              const SizedBox(height: 8),
              _buildNavButton(context, 'Home', RouteNames.home),
              const SizedBox(height: 8),
              _buildNavButton(context, 'Scan', RouteNames.scan),
              const SizedBox(height: 8),
              _buildNavButton(context, 'Manual Search', RouteNames.manualSearch),
              const SizedBox(height: 8),
              _buildNavButton(context, 'Settings', RouteNames.settings),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildNavButton(BuildContext context, String label, String route) {
    final bool isCurrent = routePath == route;
    return OutlinedButton(
      onPressed: isCurrent ? null : () => context.go(route),
      style: OutlinedButton.styleFrom(
        foregroundColor: isCurrent ? Colors.white38 : Colors.white70,
        side: BorderSide(
          color: isCurrent
              ? const Color(0xFF333333)
              : const Color(0xFF555555),
        ),
        padding: const EdgeInsets.symmetric(vertical: 12),
      ),
      child: Text(isCurrent ? '→ $label (current)' : 'Go to $label'),
    );
  }
}