// ============================================================================
// Setup QR Payload — Data extracted from admin setup QR code
//
// The admin panel generates a QR code containing a JSON string.
// This model represents the parsed and validated contents of that QR code.
//
// EXPECTED QR CODE JSON FORMAT:
// {
//   "server_url": "https://events.yourcompany.com",
//   "event_public_ref": "EVT-2024-SUMMER-001",
//   "setup_token": "tok_setup_xxxxxxxxxxxxxxxxxxxxxxxx",
//   "expires_at": "2024-12-31T23:59:59.000Z"
// }
//
// VALIDATION RULES:
// - All four fields must be present and non-empty
// - server_url must start with http:// or https://
// - expires_at must be a valid ISO 8601 datetime
// - expires_at must be in the future (not expired)
// - setup_token must be non-empty (format validation is backend responsibility)
//
// DESIGN DECISION:
// Plain Dart class with manual fromJson — not Freezed.
// This 4-field model is constructed once from JSON parsing.
// Freezed is reserved for complex sealed union types (Phase 7).
// ============================================================================

/// Parsed contents of an admin setup QR code.
///
/// Created by [SetupQrPayload.fromJson] after scanning the setup QR code.
/// Validated before proceeding to token exchange.
///
/// Immutable — all fields are final.
class SetupQrPayload {
  const SetupQrPayload({
    required this.serverUrl,
    required this.eventPublicRef,
    required this.setupToken,
    required this.expiresAt,
  });

  // ==========================================================================
  // FIELDS
  // ==========================================================================

  /// Base URL of the backend server.
  ///
  /// Used as the Dio base URL for the setup token exchange request,
  /// and stored as the session server URL after successful exchange.
  ///
  /// Examples:
  /// - 'https://tickets.yourcompany.com'
  /// - 'http://192.168.1.100:8000' (local development)
  final String serverUrl;

  /// Public event reference identifier.
  ///
  /// Scopes the setup token to a specific event.
  /// Sent with the token exchange request so the backend can validate
  /// that this setup token belongs to the expected event.
  ///
  /// Example: 'EVT-2024-SUMMER-FEST-001'
  final String eventPublicRef;

  /// One-time setup token for the scanner registration flow.
  ///
  /// Generated by the admin panel, embedded in the QR code.
  /// Exchanged with the backend for a scanner session token.
  /// This token is single-use — it becomes invalid after exchange.
  ///
  /// ⚠ Never store this token after the exchange.
  /// The scanner session token (returned by the backend) is what gets stored.
  final String setupToken;

  /// Expiry timestamp of this setup QR code.
  ///
  /// The QR code is invalid after this time.
  /// Checked locally before sending the token exchange request.
  /// Backend also validates this server-side.
  final DateTime expiresAt;

  // ==========================================================================
  // FACTORY — fromJson
  // ==========================================================================

  /// Parses a [SetupQrPayload] from a JSON map.
  ///
  /// Throws [SetupQrParseException] if:
  /// - Any required field is missing from the map
  /// - Any field is null or empty after trimming
  /// - [server_url] does not start with http:// or https://
  /// - [expires_at] is not a valid ISO 8601 datetime string
  ///
  /// Does NOT check expiry here — call [isExpired] after construction.
  ///
  /// Usage:
  /// ```dart
  /// try {
  ///   final payload = SetupQrPayload.fromJson(jsonMap);
  ///   if (payload.isExpired) {
  ///     // Show expiry error
  ///   }
  /// } on SetupQrParseException catch (e) {
  ///   // Show parse error: e.message
  /// }
  /// ```
  factory SetupQrPayload.fromJson(Map<String, dynamic> json) {
    // --- server_url ----------------------------------------------------------
    final dynamic rawServerUrl = json['server_url'];
    if (rawServerUrl == null) {
      throw const SetupQrParseException(
        field: 'server_url',
        message: 'Missing required field: server_url',
      );
    }
    final String serverUrl = rawServerUrl.toString().trim();
    if (serverUrl.isEmpty) {
      throw const SetupQrParseException(
        field: 'server_url',
        message: 'server_url cannot be empty',
      );
    }
    if (!serverUrl.startsWith('http://') && !serverUrl.startsWith('https://')) {
      throw const SetupQrParseException(
        field: 'server_url',
        message: 'server_url must start with http:// or https://',
      );
    }

    // --- event_public_ref ----------------------------------------------------
    final dynamic rawEventRef = json['event_public_ref'];
    if (rawEventRef == null) {
      throw const SetupQrParseException(
        field: 'event_public_ref',
        message: 'Missing required field: event_public_ref',
      );
    }
    final String eventPublicRef = rawEventRef.toString().trim();
    if (eventPublicRef.isEmpty) {
      throw const SetupQrParseException(
        field: 'event_public_ref',
        message: 'event_public_ref cannot be empty',
      );
    }

    // --- setup_token ---------------------------------------------------------
    final dynamic rawToken = json['setup_token'];
    if (rawToken == null) {
      throw const SetupQrParseException(
        field: 'setup_token',
        message: 'Missing required field: setup_token',
      );
    }
    final String setupToken = rawToken.toString().trim();
    if (setupToken.isEmpty) {
      throw const SetupQrParseException(
        field: 'setup_token',
        message: 'setup_token cannot be empty',
      );
    }

    // --- expires_at ----------------------------------------------------------
    final dynamic rawExpiresAt = json['expires_at'];
    if (rawExpiresAt == null) {
      throw const SetupQrParseException(
        field: 'expires_at',
        message: 'Missing required field: expires_at',
      );
    }
    final String expiresAtString = rawExpiresAt.toString().trim();
    if (expiresAtString.isEmpty) {
      throw const SetupQrParseException(
        field: 'expires_at',
        message: 'expires_at cannot be empty',
      );
    }
    final DateTime? expiresAt = DateTime.tryParse(expiresAtString);
    if (expiresAt == null) {
      throw SetupQrParseException(
        field: 'expires_at',
        message: 'expires_at is not a valid ISO 8601 datetime: "$expiresAtString"',
      );
    }

    return SetupQrPayload(
      serverUrl: serverUrl,
      eventPublicRef: eventPublicRef,
      setupToken: setupToken,
      expiresAt: expiresAt.toUtc(),
    );
  }

  // ==========================================================================
  // VALIDATION
  // ==========================================================================

  /// Returns [true] if this setup QR code has passed its expiry time.
  ///
  /// Checked immediately after parsing the QR code.
  /// If expired, the app shows an error and does not proceed to token exchange.
  ///
  /// The backend also validates expiry server-side as a second check.
  bool get isExpired => DateTime.now().toUtc().isAfter(expiresAt);

  /// Returns the number of minutes until this QR code expires.
  ///
  /// Returns 0 if already expired.
  /// Used to show "Expires in X minutes" in the confirmation sheet.
  int get minutesUntilExpiry {
    final now = DateTime.now().toUtc();
    if (now.isAfter(expiresAt)) return 0;
    return expiresAt.difference(now).inMinutes;
  }

  /// Returns the server URL with trailing slash removed.
  String get serverUrlNormalized {
    return serverUrl.endsWith('/')
        ? serverUrl.substring(0, serverUrl.length - 1)
        : serverUrl;
  }

  /// Returns a URL-safe display version (strips protocol prefix).
  String get serverUrlDisplay {
    return serverUrl
        .replaceFirst('https://', '')
        .replaceFirst('http://', '');
  }

  // ==========================================================================
  // SERIALIZATION
  // ==========================================================================

  Map<String, dynamic> toJson() {
    return {
      'server_url': serverUrl,
      'event_public_ref': eventPublicRef,
      'setup_token': setupToken,
      'expires_at': expiresAt.toIso8601String(),
    };
  }

  // ==========================================================================
  // EQUALITY AND DEBUG
  // ==========================================================================

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is SetupQrPayload &&
        other.serverUrl == serverUrl &&
        other.eventPublicRef == eventPublicRef &&
        other.setupToken == setupToken &&
        other.expiresAt == expiresAt;
  }

  @override
  int get hashCode =>
      Object.hash(serverUrl, eventPublicRef, setupToken, expiresAt);

  @override
  String toString() {
    // Never include setupToken in toString — treat it as sensitive.
    return 'SetupQrPayload('
        'serverUrl: "$serverUrl", '
        'eventPublicRef: "$eventPublicRef", '
        'setupToken: ***, '
        'expiresAt: ${expiresAt.toIso8601String()}'
        ')';
  }
}

// ============================================================================
// SETUP QR PARSE EXCEPTION
// ============================================================================

/// Thrown when a QR code cannot be parsed as a valid [SetupQrPayload].
///
/// Contains:
/// - [field]: which JSON field caused the failure (null if not field-specific)
/// - [message]: human-readable description of the parse failure
///
/// Callers should catch this and display [message] to the operator.
class SetupQrParseException implements Exception {
  const SetupQrParseException({
    required this.message,
    this.field,
  });

  /// The specific JSON field that caused the parse failure.
  /// Null if the failure is not field-specific (e.g., invalid JSON).
  final String? field;

  /// Human-readable description of the parse failure.
  /// Suitable for display in a Snackbar or error dialog.
  final String message;

  @override
  String toString() => 'SetupQrParseException: $message'
      '${field != null ? " (field: $field)" : ""}';
}